export const genreMap = {
  28: "Hành động",
  12: "Phiêu lưu",
  16: "Hoạt hình",
  35: "Hài",
  80: "Tội phạm",
  99: "Tài liệu",
  18: "Chính kịch / Tâm lý",
  10751: "Gia đình",
  14: "Giả tưởng / Thần thoại",
  36: "Lịch sử",
  27: "Kinh dị",
  10402: "Âm nhạc",
  9648: "Bí ẩn",
  10749: "Lãng mạn / Tình cảm",
  878: "Khoa học viễn tưởng",
  10770: "Phim truyền hình",
  53: "Giật gân / Ly kỳ",
  10752: "Chiến tranh",
  37: "Viễn Tây",
};
export const languageCountryMap = {
  en: "Hoa Kỳ",
  vi: "Việt Nam",
  ja: "Nhật Bản",
  ko: "Hàn Quốc",
  zh: "Trung Quốc",
  hi: "Ấn Độ",
  fr: "Pháp",
  de: "Đức",
  es: "Tây Ban Nha",
  it: "Ý",
  pt: "Brazil",
  ru: "Nga",
  th: "Thái Lan",
};



// các màu gradient
export const gradients = [
  ["#556DD9", "#7A8EE3"],
  ["#8080AB", "#A1A1C5"],
  ["#429A85", "#6FBFAF"],
  ["#8E7CC1", "#B09ED4"],
  ["#D59A83", "#E6B8A8"],
  ["#505363", "#7A7D91"],
  ["#459CA0", "#76C4C7"],
  ["#D5947A", "#E6B09B"],
  ["#6DBA67", "#9EDC97"],
  ["#B75C5C", "#D78B8B"],
  ["#B74C8A", "#D279A8"],
  ["#F087B0", "#F6AFCB"],
  ["#C65E93", "#DD8AB3"],
];



export const movies = [
  {
    id: 1,
    adult: false,
    backdrop_path: "/1RgPyOhN4DRs225BGTlHJqCudII.jpg",
    genre_ids: [16, 28, 14, 53],
    original_language: "ja",
    original_title: "Demon Slayer",
    overview:
      "Khi các thành viên của Sát Quỷ Đoàn và Trụ Cột tham gia vào chương trình đặc huấn để chuẩn bị cho trận chiến sắp với lũ quỷ, Muzan bất ngờ kéo toàn bộ Sát Quỷ Đoàn đến hang ổ cuối cùng của lũ quỷ là Vô Hạn Thành...",
    popularity: 812.6,
    poster_path: "/nV99ACeAa8fFFso0tQZ3HktEf5X.jpg",
    release_date: "2025-07-18",
    title: "Thanh gươm diệt quỷ",
    video: false,
    vote_average: 7.6,
    vote_count: 261,
  },
  {
    id: 2,
    adult: false,
    backdrop_path: "/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    genre_ids: [28, 12, 878],
    original_language: "en",
    original_title: "Avengers: Endgame",
    overview:
      "Sau thảm kịch hủy diệt của Thanos, các Avengers còn lại phải hợp sức để đảo ngược sự hủy diệt và mang lại hy vọng cho nhân loại.",
    popularity: 500.0,
    poster_path: "/9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg",
    release_date: "2019-04-24",
    title: "Avengers: Endgame",
    video: false,
    vote_average: 8.3,
    vote_count: 21000,
  },
  {
    id: 3,
    adult: false,
    backdrop_path: "/hZkgoQYus5vegHoetLkCJzb17zJ.jpg",
    genre_ids: [18],
    original_language: "en",
    original_title: "Fight Club",
    overview:
      "Một nhân viên văn phòng bất mãn và một tay buôn xà phòng thành lập câu lạc bộ đánh nhau ngầm.",
    popularity: 350.1,
    poster_path: "/hZkgoQYus5vegHoetLkCJzb17zJ.jpg",
    release_date: "1999-10-15",
    title: "Fight Club",
    video: false,
    vote_average: 8.4,
    vote_count: 26000,
  },
  {
    id: 4,
    adult: false,
    backdrop_path: "/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    genre_ids: [12, 878, 28],
    original_language: "en",
    original_title: "Avatar: The Way of Water",
    overview:
      "Jake Sully cùng gia đình phải rời nhà và tìm kiếm nơi trú ẩn an toàn khi một mối đe dọa mới xuất hiện.",
    popularity: 600.2,
    poster_path: "/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    release_date: "2022-12-14",
    title: "Avatar 2",
    video: false,
    vote_average: 7.7,
    vote_count: 12000,
  },
  {
    id: 5,
    adult: false,
    backdrop_path: "/pFlaoHTZeyNkG83vxsAJiGzfSsa.jpg",
    genre_ids: [28, 14],
    original_language: "en",
    original_title: "Black Adam",
    overview:
      "Câu chuyện về nguồn gốc của Black Adam, phản anh hùng cổ đại được giải phóng sau gần 5.000 năm bị giam cầm.",
    popularity: 700.5,
    poster_path: "/r7XifzvtezNt31ypvsmb6Oqxw49.jpg",
    release_date: "2022-10-19",
    title: "Black Adam",
    video: false,
    vote_average: 6.9,
    vote_count: 5000,
  },
  {
    id: 6,
    adult: false,
    backdrop_path: "/hqkIcbrOHL86UncnHIsHVcVmzue.jpg",
    genre_ids: [28, 80, 18],
    original_language: "en",
    original_title: "The Dark Knight",
    overview:
      "Batman phải đối đầu với Joker, kẻ tội phạm thiên tài gieo rắc hỗn loạn khắp thành phố Gotham.",
    popularity: 650.0,
    poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    release_date: "2008-07-16",
    title: "The Dark Knight",
    video: false,
    vote_average: 9.0,
    vote_count: 28000,
  },
  {
    id: 7,
    adult: false,
    backdrop_path: "/s3TBrRGB1iav7gFOCNx3H31MoES.jpg",
    genre_ids: [28, 878, 12],
    original_language: "en",
    original_title: "Inception",
    overview:
      "Một tên trộm có khả năng xâm nhập vào giấc mơ của người khác để đánh cắp bí mật phải thực hiện một nhiệm vụ cuối cùng.",
    popularity: 620.3,
    poster_path: "/edv5CZvWj09upOsy2Y6IwDhK8bt.jpg",
    release_date: "2010-07-15",
    title: "Inception",
    video: false,
    vote_average: 8.8,
    vote_count: 24000,
  },
  {
    id: 8,
    adult: false,
    backdrop_path: "/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg",
    genre_ids: [12, 18, 878],
    original_language: "en",
    original_title: "Interstellar",
    overview:
      "Một nhóm nhà thám hiểm vượt qua hố đen để tìm kiếm ngôi nhà mới cho nhân loại.",
    popularity: 580.9,
    poster_path: "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    release_date: "2014-11-05",
    title: "Interstellar",
    video: false,
    vote_average: 8.6,
    vote_count: 23000,
  },
  {
    id: 9,
    adult: false,
    backdrop_path: "/f5F4cRhQdUbyVbB5lTNCwUzD6BP.jpg",
    genre_ids: [80, 18, 53],
    original_language: "en",
    original_title: "Joker",
    overview:
      "Câu chuyện về Arthur Fleck, một diễn viên hài thất bại bị xã hội ruồng bỏ, dần trở thành Joker.",
    popularity: 770.1,
    poster_path: "/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
    release_date: "2019-10-02",
    title: "Joker",
    video: false,
    vote_average: 8.2,
    vote_count: 21000,
  },
  {
    id: 10,
    adult: false,
    backdrop_path: "/5weKu49pzJCt06OPpjvT80efnQj.jpg",
    genre_ids: [28, 12, 878],
    original_language: "en",
    original_title: "Spider-Man: No Way Home",
    overview:
      "Peter Parker tìm kiếm sự giúp đỡ của Doctor Strange để khôi phục bí mật thân phận, nhưng mọi thứ vượt ngoài tầm kiểm soát.",
    popularity: 900.2,
    poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    release_date: "2021-12-15",
    title: "Spider-Man: No Way Home",
    video: false,
    vote_average: 8.0,
    vote_count: 18000,
  },
];